---
title: "Assigment_1 Fml"
author: "AJAY SHADAM"
date: "2023-09-24"
output:
  pdf_document: default
  html_document: default
---
#Download the Dataset called "telangana-post-monsoon-ground-water-quality-data" from the source (datasource:https://www.kaggle.com/datasets/sivapriyagarladinne/telangana-post-monsoon-ground-water-quality-data?resource=download)

```{r}
#Below function reads the csv file which is donwloaded and loads it into a dataframe -"my_file".
my_file <-read.csv("C:/Users/Ajay Reddy/Downloads/ground_water_quality_2018_post.csv")
#prints out the full dataset.
my_file
```
```{r}
#The below functions gives statistics such as mean,median,min,max etc., for the variable 'lat_gis'.  
summary(my_file)

mean(my_file$lat_gis)

median(my_file$lat_gis)

sd(my_file$lat_gis)

var(my_file$lat_gis)

min(my_file$lat_gis)

max(my_file$lat_gis)

str(my_file$lat_gis)
```
#Gives frequency counts for the categorical variables mandal,village.

```{r}
table(my_file$mandal)

table(my_file$village)

str(my_file$mandal)
```
#transforming variables

```{r}
log(my_file$lat_gis)

log(my_file$long_gis)

s<-my_file$lat_gis-my_file$long_gis-max(my_file$lat_gis)/min(my_file$lat_gis)

s
```
#plots a histogram of the lat_gis quantitative variable

```{r}
hist(my_file$lat_gis,main = "HISTOGRAM OF PRICE")
```
#plots a scatterplot of lat_gis vs long_gis.

```{r}
plot(my_file$lat_gis,my_file$long_gis,main = "Scatterplot")
```





